# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/coope/documents/coding_projects/vrp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/coope/Documents/coding_projects/vrp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/coope/Documents/coding_projects/vrp/CMakeFiles /mnt/c/Users/coope/Documents/coding_projects/vrp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/coope/Documents/coding_projects/vrp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vrp_lib

# Build rule for target.
vrp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vrp_lib
.PHONY : vrp_lib

# fast build rule for target.
vrp_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/build
.PHONY : vrp_lib/fast

#=============================================================================
# Target rules for targets named vrp

# Build rule for target.
vrp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vrp
.PHONY : vrp

# fast build rule for target.
vrp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp.dir/build.make CMakeFiles/vrp.dir/build
.PHONY : vrp/fast

#=============================================================================
# Target rules for targets named vrp_tests

# Build rule for target.
vrp_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vrp_tests
.PHONY : vrp_tests

# fast build rule for target.
vrp_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/build
.PHONY : vrp_tests/fast

src/clarke_wright.o: src/clarke_wright.cpp.o
.PHONY : src/clarke_wright.o

# target to build an object file
src/clarke_wright.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/clarke_wright.cpp.o
.PHONY : src/clarke_wright.cpp.o

src/clarke_wright.i: src/clarke_wright.cpp.i
.PHONY : src/clarke_wright.i

# target to preprocess a source file
src/clarke_wright.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/clarke_wright.cpp.i
.PHONY : src/clarke_wright.cpp.i

src/clarke_wright.s: src/clarke_wright.cpp.s
.PHONY : src/clarke_wright.s

# target to generate assembly for a file
src/clarke_wright.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/clarke_wright.cpp.s
.PHONY : src/clarke_wright.cpp.s

src/create_child.o: src/create_child.cpp.o
.PHONY : src/create_child.o

# target to build an object file
src/create_child.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/create_child.cpp.o
.PHONY : src/create_child.cpp.o

src/create_child.i: src/create_child.cpp.i
.PHONY : src/create_child.i

# target to preprocess a source file
src/create_child.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/create_child.cpp.i
.PHONY : src/create_child.cpp.i

src/create_child.s: src/create_child.cpp.s
.PHONY : src/create_child.s

# target to generate assembly for a file
src/create_child.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/create_child.cpp.s
.PHONY : src/create_child.cpp.s

src/genetic_algo_utils.o: src/genetic_algo_utils.cpp.o
.PHONY : src/genetic_algo_utils.o

# target to build an object file
src/genetic_algo_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/genetic_algo_utils.cpp.o
.PHONY : src/genetic_algo_utils.cpp.o

src/genetic_algo_utils.i: src/genetic_algo_utils.cpp.i
.PHONY : src/genetic_algo_utils.i

# target to preprocess a source file
src/genetic_algo_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/genetic_algo_utils.cpp.i
.PHONY : src/genetic_algo_utils.cpp.i

src/genetic_algo_utils.s: src/genetic_algo_utils.cpp.s
.PHONY : src/genetic_algo_utils.s

# target to generate assembly for a file
src/genetic_algo_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/genetic_algo_utils.cpp.s
.PHONY : src/genetic_algo_utils.cpp.s

src/genetic_algorithm.o: src/genetic_algorithm.cpp.o
.PHONY : src/genetic_algorithm.o

# target to build an object file
src/genetic_algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/genetic_algorithm.cpp.o
.PHONY : src/genetic_algorithm.cpp.o

src/genetic_algorithm.i: src/genetic_algorithm.cpp.i
.PHONY : src/genetic_algorithm.i

# target to preprocess a source file
src/genetic_algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/genetic_algorithm.cpp.i
.PHONY : src/genetic_algorithm.cpp.i

src/genetic_algorithm.s: src/genetic_algorithm.cpp.s
.PHONY : src/genetic_algorithm.s

# target to generate assembly for a file
src/genetic_algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/genetic_algorithm.cpp.s
.PHONY : src/genetic_algorithm.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp.dir/build.make CMakeFiles/vrp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp.dir/build.make CMakeFiles/vrp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp.dir/build.make CMakeFiles/vrp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_lib.dir/build.make CMakeFiles/vrp_lib.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

tests/test_clarke_wright.o: tests/test_clarke_wright.cpp.o
.PHONY : tests/test_clarke_wright.o

# target to build an object file
tests/test_clarke_wright.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/tests/test_clarke_wright.cpp.o
.PHONY : tests/test_clarke_wright.cpp.o

tests/test_clarke_wright.i: tests/test_clarke_wright.cpp.i
.PHONY : tests/test_clarke_wright.i

# target to preprocess a source file
tests/test_clarke_wright.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/tests/test_clarke_wright.cpp.i
.PHONY : tests/test_clarke_wright.cpp.i

tests/test_clarke_wright.s: tests/test_clarke_wright.cpp.s
.PHONY : tests/test_clarke_wright.s

# target to generate assembly for a file
tests/test_clarke_wright.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/tests/test_clarke_wright.cpp.s
.PHONY : tests/test_clarke_wright.cpp.s

tests/test_genetic_algorithm.o: tests/test_genetic_algorithm.cpp.o
.PHONY : tests/test_genetic_algorithm.o

# target to build an object file
tests/test_genetic_algorithm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/tests/test_genetic_algorithm.cpp.o
.PHONY : tests/test_genetic_algorithm.cpp.o

tests/test_genetic_algorithm.i: tests/test_genetic_algorithm.cpp.i
.PHONY : tests/test_genetic_algorithm.i

# target to preprocess a source file
tests/test_genetic_algorithm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/tests/test_genetic_algorithm.cpp.i
.PHONY : tests/test_genetic_algorithm.cpp.i

tests/test_genetic_algorithm.s: tests/test_genetic_algorithm.cpp.s
.PHONY : tests/test_genetic_algorithm.s

# target to generate assembly for a file
tests/test_genetic_algorithm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vrp_tests.dir/build.make CMakeFiles/vrp_tests.dir/tests/test_genetic_algorithm.cpp.s
.PHONY : tests/test_genetic_algorithm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... vrp"
	@echo "... vrp_lib"
	@echo "... vrp_tests"
	@echo "... src/clarke_wright.o"
	@echo "... src/clarke_wright.i"
	@echo "... src/clarke_wright.s"
	@echo "... src/create_child.o"
	@echo "... src/create_child.i"
	@echo "... src/create_child.s"
	@echo "... src/genetic_algo_utils.o"
	@echo "... src/genetic_algo_utils.i"
	@echo "... src/genetic_algo_utils.s"
	@echo "... src/genetic_algorithm.o"
	@echo "... src/genetic_algorithm.i"
	@echo "... src/genetic_algorithm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... tests/test_clarke_wright.o"
	@echo "... tests/test_clarke_wright.i"
	@echo "... tests/test_clarke_wright.s"
	@echo "... tests/test_genetic_algorithm.o"
	@echo "... tests/test_genetic_algorithm.i"
	@echo "... tests/test_genetic_algorithm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

