name: VRP Tests

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libomp-dev

    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        cmake -S . -B build -DBUILD_TESTING=OFF
        sudo cmake --build build --target install

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build

    - name: Run tests
      run: ./build/vrp_tests